# Generated by Django 5.1.6 on 2025-05-18 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_userprogress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
