# Generated by Django 5.1.6 on 2025-05-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_userprogress_attempted_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
    ]
